language: rust
rust: stable

os:
  - linux
  - osx

env:
  - NODE_VERSION='8.10.0'

cache:
  - cargo
  - npm
  - directories:
    - /home/travis/build/Nu-SCPTheme/scipnet/ftml-json/target

before_script:
  - git submodule init
  - git submodule update
  - nvm install $NODE_VERSION
  - (cd frontend && npm install)
  - (cd backend && npm install)

script: make
